materia/config/routes.rb
Rails.application.routes.draw do
  resources :materia

end

materia/app/models/materium.rb
class Materium < ActiveRecord::Base
end

materia/app/controllers/materia_controller.rb
class MateriaController < ApplicationController
  before_action :set_materium, only: [:show, :edit, :update, :destroy]

  # GET /materia
  # GET /materia.json
  def index
    @materia = Materium.all
  end

  # GET /materia/1
  # GET /materia/1.json
  def show
  end

  # GET /materia/new
  def new
    @materium = Materium.new
  end

  # GET /materia/1/edit
  def edit
  end

  # POST /materia
  # POST /materia.json
  def create
    @materium = Materium.new(materium_params)

    respond_to do |format|
      if @materium.save
        format.html { redirect_to @materium, notice: 'Materium was successfully created.' }
        format.json { render :show, status: :created, location: @materium }
      else
        format.html { render :new }
        format.json { render json: @materium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materia/1
  # PATCH/PUT /materia/1.json
  def update
    respond_to do |format|
      if @materium.update(materium_params)
        format.html { redirect_to @materium, notice: 'Materium was successfully updated.' }
        format.json { render :show, status: :ok, location: @materium }
      else
        format.html { render :edit }
        format.json { render json: @materium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materia/1
  # DELETE /materia/1.json
  def destroy
    @materium.destroy
    respond_to do |format|
      format.html { redirect_to materia_url, notice: 'Materium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materium
      @materium = Materium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def materium_params
      params.require(:materium).permit(:materia, :profesor, :codigo)
    end
end

materia/app/helpers/materia_helper.rb
module MateriaHelper
end

materia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Materia</title>

</head>
<body>

<%= yield %>

</body>
</html>

materia/app/views/materia/_form.html.erb
<%= form_for(@materium) do |f| %>
  <% if @materium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@materium.errors.count, "error") %> prohibited this materium from being saved:</h2>

      <ul>
      <% @materium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :materia %><br>
    <%= f.text_field :materia %>
  </div>
  <div class="field">
    <%= f.label :profesor %><br>
    <%= f.text_field :profesor %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.number_field :codigo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

materia/app/views/materia/edit.html.erb
<h1>Editing Materium</h1>

<%= render 'form' %>

<%= link_to 'Show', @materium %>
<%= link_to 'Back', materia_path, class: 'button' %>

materia/app/views/materia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Materia</h1>

<table>
  <thead>
    <tr>
      <th>Materia</th>
      <th>Profesor</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materia.each do |materium| %>
      <tr>
        <td><%= materium.materia %></td>
        <td><%= materium.profesor %></td>
        <td><%= materium.codigo %></td>
        <td><%= link_to 'Show', materium class:'button' %></td>
        <td><%= link_to 'Edit', edit_materium_path(materium class:'button) %></td>
        <td><%= link_to 'Destroy', materium class:'button, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Materium', new_materium_path %>

materia/app/views/materia/new.html.erb
<h1>New Materium</h1>

<%= render 'form' %>

<%= link_to 'Back', materia_path %>

materia/app/views/materia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Materia:</strong>
  <%= @materium.materia %>
</p>

<p>
  <strong>Profesor:</strong>
  <%= @materium.profesor %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @materium.codigo %>
</p>

<%= link_to 'Edit', edit_materium_path(@materium) %> |
<%= link_to 'Back', materia_path %>